ALTER TABLE users
ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE tokens
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE tokens
ADD COLUMN IF NOT EXISTS consumed_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE tokens
ADD COLUMN IF NOT EXISTS invalidated_at TIMESTAMP WITH TIME ZONE;

CREATE INDEX IF NOT EXISTS idx_tokens_type_hash ON tokens(type, token_hash);
