ALTER TABLE sessions
    ADD COLUMN IF NOT EXISTS device VARCHAR(255) NOT NULL DEFAULT 'Unknown device',
    ADD COLUMN IF NOT EXISTS browser VARCHAR(255) NOT NULL DEFAULT 'Unknown browser',
    ADD COLUMN IF NOT EXISTS os VARCHAR(255) NOT NULL DEFAULT 'Unknown OS',
    ADD COLUMN IF NOT EXISTS ip VARCHAR(64) NOT NULL DEFAULT 'Unknown IP',
    ADD COLUMN IF NOT EXISTS location VARCHAR(255) NOT NULL DEFAULT 'Unknown location',
    ADD COLUMN IF NOT EXISTS last_active_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS notification_preferences (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    email_notifications BOOLEAN NOT NULL DEFAULT true,
    push_notifications BOOLEAN NOT NULL DEFAULT true,
    marketing_emails BOOLEAN NOT NULL DEFAULT false,
    security_alerts BOOLEAN NOT NULL DEFAULT true,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
