name: scorecard
on:
  push:
    branches:
      - main
  schedule:
    - cron: "23 3 * * 1"
  branch_protection_rule:
permissions: read-all
jobs:
  analysis:
    name: OpenSSF Scorecard
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
      issues: read
      pull-requests: read
      checks: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@99c09fe975337306107572b4fdf4db224cf8e2f2
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
          # Uncomment if this repository is private or if the Branch-Protection
          # check needs a fine-grained PAT instead of repository rules.
          # repo_token: ${{ secrets.SCORECARD_READ_TOKEN }}
      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@38b3b7bf288d49ccf58644769dc7a6afdccd05eb
        with:
          sarif_file: results.sarif
